[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
transfer_hook = "BPu1HGsLmA3PEPW4rCW7fUYYKPNQ1vAPWytvBwr5nuM3"
whitelist_manager = "63YybmV5S1uZdPoXRCUHP5LR34maufSGW4bNaT2GmLMj"
business_id_factory = "35y1BTgc6QzvGYL6raYNJJf6j136ZfQcssWHKKr8rCRf"
stablecoin_ramp = "7Yh27as26FVuh5Hqeq9EpwyKUukiu5RKcgtPsqXrEVeg"
oft = "9UovNrJD8pQyBLheeHNayuG1wJSEAoxkmM14vw5gcsTT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=7c8a6828-2b0b-456b-a1fc-f08073e8304a"
wallet = "~/.config/solana/id.json"

[scripts]
deploy = "ts-node migrations/deploy.ts"
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://devnet.helius-rpc.com/?api-key=7c8a6828-2b0b-456b-a1fc-f08073e8304a"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
